from tkinter import *
import webbrowser
root = Tk()
root.title("Page Open Bot")
root.geometry("750x580")
root.iconbitmap('Brand-Logo-Icon.ico')
root.resizable(False, False)
root.configure(bg='lemon chiffon')
appLabel = Label(root, text="Open the pages you want !!", font=("Times", "42", "bold italic"), fg="red", bg='lemon chiffon', anchor=CENTER)
appLabel.pack()
appLabel.place(x=10,y=5)
pageNo_frame = LabelFrame(root, text="Select No. of Pages", background="lemon chiffon", bd=4, fg='red', labelanchor=N)
from_label = Label(pageNo_frame, text="From: ", background="lemon chiffon")
from_label.grid(row=0, column=0, padx=10, pady=10)
from_entry = Entry(pageNo_frame)
from_entry.grid(row=0, column=1, padx=10, pady=10)
to_label = Label(pageNo_frame, text="To: ", background="lemon chiffon")
to_label.grid(row=0, column=2, padx=10, pady=10)
to_entry = Entry(pageNo_frame)
to_entry.grid(row=0, column=3, padx=10, pady=10)
def open():
    from_page_no = int(from_entry.get())
    to_page_no = int(to_entry.get())
    for i in range(from_page_no, to_page_no):
        url = "https:/www.askmattrab.com/notes/"+str(i)
        #print(url)
        webbrowser.open_new(url)
    last_url = "https:/www.askmattrab.com/notes/"+str(to_page_no)
    webbrowser.open_new(last_url)
    #print(last_url)
open_button = Button(root, text="Open Pages", fg='white', bg='red', font=("Helvetica", "11", "italic"), bd='3', command=open)
open_button.pack()
open_button.place(x=250, y=250)
pageNo_frame.pack()
pageNo_frame.place(x=40, y=100)
root.mainloop()
